### ISSUE TITLE
k8s registry failed on a kind test

### ISSUE THREAD

**Issue by artem-belov** [networkservicemesh/sdk-k8s#82]
```
panic: interface conversion: runtime.Object is *v1.Status, not *v1.NetworkServiceEndpoint
goroutine 109 [running]:
github.com/networkservicemesh/sdk-k8s/pkg/registry/etcd.(*etcdNSERegistryServer).watch(0xc000493140, 0xc0001c6280, 0x18ac7a0, 0xc00045c480, 0x0, 0x0)
	/go/pkg/mod/github.com/networkservicemesh/sdk-k8s@v0.0.0-20210317140517-bc14cb41f960/pkg/registry/etcd/nse_server.go:126 +0x486
github.com/networkservicemesh/sdk-k8s/pkg/registry/etcd.(*etcdNSERegistryServer).Find(0xc000493140, 0xc0001c6280, 0x18ac7a0, 0xc00045c480, 0xc0001c6280, 0xc00000cb40)
	/go/pkg/mod/github.com/networkservicemesh/sdk-k8s@v0.0.0-20210317140517-bc14cb41f960/pkg/registry/etcd/nse_server.go:92 +0x2c5
github.com/networkservicemesh/sdk/pkg/registry/core/trace.(*traceNetworkServiceEndpointRegistryServer).Find(0xc0006abad0, 0xc0001c6280, 0x18ac620, 0xc00000c980, 0x0, 0x0)
	/go/pkg/mod/github.com/networkservicemesh/sdk@v0.0.0-20210317140009-9204d6f8efcc/pkg/registry/core/trace/nse_registry.go:174 +0x231
github.com/networkservicemesh/sdk/pkg/registry/core/next.(*nextNetworkServiceEndpointRegistryServer).Find(0xc0004ae270, 0xc0001c6280, 0x18ac7a0, 0xc00045c290, 0x2, 0xc00000c8b0)
	/go/pkg/mod/github.com/networkservicemesh/sdk@v0.0.0-20210317140009-9204d6f8efcc/pkg/registry/core/next/nse_registry_server.go:62 +0x1d9
github.com/networkservicemesh/sdk/pkg/registry/common/expire.(*expireNSEServer).Find(0xc000312840, 0xc0001c6280, 0x18ac7a0, 0xc00045c290, 0xc0001c6280, 0xc00000c920)
	/go/pkg/mod/github.com/networkservicemesh/sdk@v0.0.0-20210317140009-9204d6f8efcc/pkg/registry/common/expire/nse_server.go:135 +0x7f
github.com/networkservicemesh/sdk/pkg/registry/core/trace.(*traceNetworkServiceEndpointRegistryServer).Find(0xc0006abac0, 0xc0001c6280, 0x18ac620, 0xc00000c700, 0x0, 0x0)
	/go/pkg/mod/github.com/networkservicemesh/sdk@v0.0.0-20210317140009-9204d6f8efcc/pkg/registry/core/trace/nse_registry.go:174 +0x231
github.com/networkservicemesh/sdk/pkg/registry/core/next.(*nextNetworkServiceEndpointRegistryServer).Find(0xc000493170, 0xc0001c6280, 0x18ac260, 0xc00045c160, 0xc000493170, 0x20)
	/go/pkg/mod/github.com/networkservicemesh/sdk@v0.0.0-20210317140009-9204d6f8efcc/pkg/registry/core/next/nse_registry_server.go:62 +0x1d9
github.com/networkservicemesh/api/pkg/api/registry._NetworkServiceEndpointRegistry_Find_Handler(0x15398e0, 0xc000493170, 0x18a7460, 0xc00000c6c0, 0x1689ee0, 0xc000458100)
	/go/pkg/mod/github.com/networkservicemesh/api@v0.0.0-20210305165706-bcfdc8d78700/pkg/api/registry/registry.pb.go:864 +0x10b
github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingStreamServerInterceptor.func1(0x15398e0, 0xc000493170, 0x18a7580, 0xc0001060c0, 0xc00000c520, 0x1772a58, 0x0, 0x0)
	/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:114 +0x370
google.golang.org/grpc.(*Server).processStreamingRPC(0xc00014d340, 0x18afaa0, 0xc000582300, 0xc000458000, 0xc0004934a0, 0x21bdd60, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:1471 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc00014d340, 0x18afaa0, 0xc000582300, 0xc000458000, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:1544 +0xc9c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0004a0ef0, 0xc00014d340, 0x18afaa0, 0xc000582300, 0xc000458000)
	/go/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:878 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.35.0/server.go:876 +0x1fd
```

**Comment by artem-belov** [comment]
Steps to reproduce: repeat steps from [Memif2Memif](https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/use-cases/Memif2Memif)

**Comment by Bolodya1997** [comment]
looks like an error in code:
https://github.com/networkservicemesh/sdk-k8s/blob/bc14cb41f960bbbd93e041eb7ccbb92628a79550/pkg/registry/etcd/nse_server.go#L125-L126
because `Object` can be `Status` instead of `Endpoint` if `EventType == Error`
```go
type Event struct {
	Type EventType
	// Object is:
	...
	//  * If Type is Error: *api.Status is recommended; other types may make sense
	//    depending on context.
	Object runtime.Object
}
```
